#spring.application.name=vcsvpl-api
spring:
  datasource:
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:24275/railway
    username: postgres
    password: EhmSgQTzEGSFBwYZBmpiRaknhvOivNEB
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
    #for test
    show-sql: true